### ISSUE TITLE
Fix for raspberry 7 inch display

### ISSUE THREAD

**Issue by colder1989** [radxa-build/rock-4c-plus#3]
using the latest release (20221001-0214), if I enable the 7 inch raspberry display from boot/hw_intfc.conf, the operating system will no longer boot.
how can it be solved?

**Comment by RadxaYuntian** [comment]
Hi @colder1989. Today's test image should fix the support for Raspberry Pi Touchscreen.

The new account is radxa/radxa. By default SSH is disabled. If you want to enable SSH, please edit `before.txt` file after you flashed the image to the SD card. After log into the system, you can run `rsetup` to enable the required overlay.
