### ISSUE TITLE
Ubuntu jammy cli is not booting up after flashing with balena

### ISSUE THREAD

**Issue by ngkkneel** [radxa-build/rock-4c-plus#4]
None of Ubuntu Jammy images are booting up. 

Ubuntu jammy cli is not booting up after flashing with balena

**Comment by ngkkneel** [comment]
Hardware: Rock PI 4C plus
Image: rock-4c-plus_ubuntu_jammy_cli_b55.img.xz

**Comment by RadxaYuntian** [comment]
@RadxaNaoki can you check what's going on with Ubuntu. I think currently all our Ubuntu image is not bootable.

**Comment by ngkkneel** [comment]
> @RadxaNaoki can you check what's going on with Ubuntu. I think currently all our Ubuntu image is not bootable.

Thanks @RadxaYuntian  Hi @RadxaNaoki could you please look into this? Hopefully this gets resolved soon in order for me to continue my work. I'm stuck. Your help greatly appreciated. thanks.

**Comment by RadxaYuntian** [comment]
Naoki found there is difference in Ubuntu's `u-boot-menu` package, which we use to create the boot entry. He is still working on this.

I think you also wrote an email to us, so let's keep the conversation here.

**Comment by ngkkneel** [comment]
Hi @RadxaNaoki , It's been quite a long time this issue was logged. Have you got a chance to fix the u-boot-menu package? Thanks

**Comment by RadxaYuntian** [comment]
That issue is resolved. Currently we are planning for a new 4SE image release soon, and test images for 4C+ will follow.
