### ISSUE TITLE
Current images don't appear to have working wifi

### ISSUE THREAD

**Issue by marcone** [radxa-build/rock-4c-plus#7]
`nmtui` shows no available wifi connections, only the wired connection. I tried [rock-4c-plus_debian_bullseye_cli_b59.img.xz](https://github.com/radxa-build/rock-4c-plus/releases/download/20230601-0144/rock-4c-plus_debian_bullseye_cli_b59.img.xz) and [rock-4c-plus_ubuntu_jammy_cli_b59.img.xz](https://github.com/radxa-build/rock-4c-plus/releases/download/20230601-0144/rock-4c-plus_ubuntu_jammy_cli_b59.img.xz)

**Comment by RadxaYuntian** [comment]
First off, [b59](https://github.com/radxa-build/rock-4c-plus/releases/tag/20230601-0144) is marked as pre-release. It is not an official release and we do not support them.

The [latest test build](https://github.com/radxa-build/rock-4c-plus/releases/download/test-build-2/rock-4c-plus_debian_bullseye-test_cli_t2.img.xz) (t2) has working Wi-Fi out of the box, which reflects the current code status.

The [latest production release](https://github.com/radxa-build/rock-4c-plus/releases/download/20230312-1521/rock-4c-plus_debian_bullseye_cli_b55.img.xz) (b55) also has working Wi-Fi out of the box. I also tested after full system upgrade, and the Wi-Fi still works after the upgrade.

I also tested b59 just in case and Wi-Fi is, again, working on my 4C+.

Please check if you have connected the antenna on your 4C+. It is mandatory to get Wi-Fi signal.

**Comment by marcone** [comment]
On b59, `ifconfig` will show the wlan0 interface, however it does not show up in `nmtui` and `nmcli` shows wlan0 as "unavailable". I also noticed that `nmtui` doesn't have its usual blue background, in case that is relevant.

`nmtui` does work as expected on the latest test build.

**Comment by RadxaYuntian** [comment]
I tested all 3 images with `nmtui` as well but glad you can at least get it working on the latest build.

The background is due to terminal setting, but does not change functionality. In case you are curious it is set [here](https://github.com/radxa-pkg/radxa-system-config/blob/main/radxa-system-config-common/usr/lib/systemd/system/serial-getty%40.service.d/10-term.conf).
