### ISSUE TITLE
CANCELLED

### ISSUE THREAD

**Issue by fvalasiad** [radxa-build/rock-4c-plus#8]

**Comment by RadxaYuntian** [comment]
1. We maintain several package repositories that allows the system to be upgraded online, so there is no reason to release a new image if it is not broken.
2. Rockchip has not released a new SDK for RK3399, so we are stuck with what we have.
3. We are experimenting with RK3588 Linux 6.1 SDK to see if it can support RK3399.

**Comment by fvalasiad** [comment]
> 1. We maintain several package repositories that allows the system to be upgraded online, so there is no reason to release a new image if it is not broken.
> 2. Rockchip has not released a new SDK for RK3399, so we are stuck with what we have.
> 3. We are experimenting with RK3588 Linux 6.1 SDK to see if it can support RK3399.

You responded anyway, thanks!

Cool so I can confidently install it. Releasing a new image is indeed unnecessary given that it's debian, it's just that uncertainty got the best of me.

Thanks again, I'll be joining ya soon!
